web:
  build: .
  command: sh -c 'npm install; npm start'
  ports:
    - '4000:4000'
  volumes:
    - /home/axel/Escritorio/api_superheroes/api:/api
  links:
    - "db:mongo"
db:
  image: mongo
  ports:
    - "27017:27017"

